### ISSUE TITLE
Adicionar novo Tipo de Fieldset

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#1]
Adicionar novo "type Fieldset" com suporte a multiplos input's no mesmo componente. Necessário para o cadastro de Orçamento, em que no mesmo componente terá Input de (Texto, Checkbox e Valor Numérico)

**Comment by nalomysouza** [comment]
criar campos para Orçamento Simplificado, Cronograma de Execução e publicação de Plano de Trabalho #15

**Comment by jacksoncastro** [comment]
@geciola  para a criação desse novo input é necessário uma mudança estrutural do projeto, no qual não é possível de ser feita em um tema. Foi criada uma atividade para isso no Core: hacklabr/mapasculturais#1008

**Comment by nalomysouza** [comment]
é necessário uma mudança estrutural do projeto, no qual não é possível de ser feita em um tema. Foi criada uma atividade para isso no Core: hacklabr/mapasculturais#1008
