### ISSUE TITLE
Possibilitar projetos e os eventos aparecer no histórico de todos os agentes participantes

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#14]
Os projetos e os eventos devem aparecer no histórico de todos os agentes responsáveis por ele, e não só no perfil do agente que criou o projeto;

**Comment by jacksoncastro** [comment]
Está atividade já está sendo resolvida em culturagovbr/mapasculturais#29

**Comment by nalomysouza** [comment]
Atividade solucionada https://github.com/culturagovbr/mapasculturais/issues/29
