### ISSUE TITLE
Adicionar novo formato de exportação dos eventos

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#16]
Opção para exportar a pesquisa no formato kmz do Google Earth ou com as referências geográficas dos eventos;

**Comment by jacksoncastro** [comment]
Qual o propósito dessa funcionalidade?

Utilizar uma coluna na planilha, com um link como por exemplo: "Abrir no Google Earth", abrindo assim o evento externamente? Ou só é necessário o .kmz como no exemplo a seguir:

`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Placemark>
    <name>Simple placemark</name>
    <description>Attached to the ground. Intelligently places itself 
       at the height of the underlying terrain.</description>
    <Point>
      <coordinates>-122.0822035425683,37.42228990140251,0</coordinates>
    </Point>
  </Placemark>
</kml>`
