### ISSUE TITLE
Possibilitar a fase de curadoria dentro do Mapa.

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#20]
Abrir notas para pareceristas em três momentos (seleção, ranking e recursos)

**Comment by jacksoncastro** [comment]
Aguardando tramite entre hacklab e @uira. Pois possívelmente está atividade será resolvida em um novo pacote de melhorias.

**Comment by nalomysouza** [comment]
Está sendo desenvolvido pela Hacklab
