### ISSUE TITLE
Desenvolver Termo de Uso do Mapa

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#22]
Importante passo antes da migração dos servidores da TIM para a SECULT

**Comment by nalomy** [comment]
Nalomy enviar para Gecíola trechos da Lei de Acesso à Informação e Marco Civil da Internet

**Comment by geciola** [comment]
@nalomy enviar para Gecíola trechos da Lei de Acesso à Informação e Marco Civil da Internet

**Comment by nalomysouza** [comment]
Comentei no google sobre aponto sobre a Lei de acesso a informação. Li sobre os trechos citados novamente e por se tratar de um termo, ou "contrato" que tem embasamento jurídico. Creio que esse termo deve ser bastante revisto antes, principalmente por não termos perícia no assunto. E isso pode ocasionar grandes problemas.
