### ISSUE TITLE
Customizar Login Cidadão para o MapaCeara

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#24]
Implementar Login Cidadão (ID Ceará: solicitar id.ce.gov.br) e tirar "Permitir usar ID da Cultura"

a) Ver documentação com Donato com passo a passo para integração com Mapa. Brasília, SP, Santo André já implementaram.

**Comment by geciola** [comment]
@nalomy enviar email para Uirá, Donato e Felipe solicitando documentação do Login Cidadão.

**Comment by JuniorGiglioli** [comment]
url da documentação : http://redelivre.github.io/login-cidadao/lc_deploy/#integrando-com-o-mapas-culturais
