### ISSUE TITLE
Ajustar redirecionamento de url do mapas

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#26]
Direcionar www.mapa.cultura.ce.gov.br para mapa.cultura.ce.gov.br

**Comment by nalomysouza** [comment]
Ambos os Endereços www.mapa.cultura.ce.gov.br e  http://mapa.cultura.ce.gov.br estão apontando para ceara.map.as (198.58.109.56) conforme confirmação pela ETICE e analise de DNS (https://dnschecker.org/)

**Comment by jacksoncastro** [comment]
Conforme analisado, o problema consiste em alterar o arquivo de resolução de endereços (geralmente arquivo /etc/hosts) no servidor em que o serviço foi hospedado.

Para isso solicitamos dentro do chat da hacklab (http://chat.mapasculturais.org/channel/mapa-ceara) a solução do problema.
