### ISSUE TITLE
Permitir acesso ao sistema somente após confirmação de email

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#27]
Só permitir acesso ao sistema para cadastro de agentes e/ou de grupos e/ou de eventos depois da confirmação do e-mail (login cidadão resolve)

**Comment by jacksoncastro** [comment]
@geciola o mapas não possui um sistema de autenticação próprio. No caso a ferramenta autenticadora é que deve verificar isso. Se a solução adotada for o login cidadão, a mesma já resolve.
Login cidadão vai ser o meio autenticador, ou será utilizado outra ferramenta?

**Comment by nalomysouza** [comment]
Processo só pode ser realizado com a migração da autenticação para o login cidadao
