### ISSUE TITLE
Criar selos diversos para eventos

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#31]
Criar selos diversos para eventos com apoio financeiro, cultural ou com reconhecimento da Secult etc (definir nomes)

**Comment by jacksoncastro** [comment]
@geciola  já existe uma funcionalidade para a criação de selos, porém ela não está habilitada para o tema do Ceará. O link da funcionalidade é /selos/create. Também pode ser acessado através do painel principal da aplicação.

Para a habilitação do selo no mapas deve ser adicionado a seguinte regra no config.php ou conf-base.php do tema: 
`'app.enabled.seals'   => true`

**Comment by nalomysouza** [comment]
Não estamos utilizando os selos. Contudo, existe tal possibilidade
