### ISSUE TITLE
Rever obrigatoriedade de dados no cadastro para inscrição em editais

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#32]
Rever obrigatoriedade de dados no cadastro para inscrição em editais. Hoje são poucos dados obrigatórios. É importante a obrigatoriedade do endereço completo, por exemplo, para geração de indicadores

**Comment by jacksoncastro** [comment]
@geciola Informar os campos que deverão ser obrigatórios

**Comment by Andreqlp** [comment]
Essas são as informações que estão sendo solicitadas de forma obrigatória para os proponentes:

PESSOA FÍSICA
Nome Completo do proponente 
Nome Artístico/Nome Social
RG - Registro Geral (Cédula de Identidade)*
CPF - Cadastro Pessoa Física 
Endereço completo, com CEP
Telefone 1
E-mail Privado
Data de Nascimento 
Gênero
Estado Civil


PESSOA JURÍDICA 
Nome da Razão Social
Nome Fantasia
CNPJ - Cadastro Nacional de Pessoa Jurídica
Nome, RG e CPF do Representante Legal*
Endereço completo da instituição, com CEP
Telefone 1
E-mail Privado
Data de Fundação

Como se pode ser, existem campos que são específicos para cada tipo de pessoa (física ou jurídica) e outros que não existem (marcados de *). 

Imagino que, nesse primeiro momento, seja para tornar obrigatórios os campos que já existem. Detalhe, **a prioridade dessa issue é Alta.**

**Comment by geciola** [comment]
Atualização da lista enviada pelo Jedi:

PESSOA FÍSICA
I - Nome Completo do Proponente;
II - Nome Artístico/Nome Social;
III - RG - Registro Geral (Cédula de Identidade);
IV - Data de Expedição (RG);
V - Órgão Expedidor (RG);
VI - UF do RG; 
VII - CPF - Cadastro Pessoa Física;
VIII - Endereço Completo, com CEP;
IX - Telefone fixo e celular;
X - E-mails;
XI - Data de Nascimento; 
XII - Gênero;
XIII - Estado Civil.


PESSOA JURÍDICA 
I - Nome da Razão Social;
II - Nome Fantasia;
III - CNPJ - Cadastro Nacional de Pessoa Jurídica;
IV-  Data de Fundação;
V - Código / Natureza Jurídica;
VI - Código / Atividade Principal;
VII - Endereço Comercial, com CEP;
VIII - Telefone fixo e celular;
IX - E-mails;
X - Dirigente, RG com órgão expedidor, data de expedição, CPF, Cargo, endereço residencial, telefones e emails.

**Comment by uira** [comment]
@geciola Gente, a demanda é deixar isso opcional para cada edital, é issp?
