### ISSUE TITLE
Criação de grupos (papéis)

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#33]
Níveis de acesso diferentes (visualização, edição etc) por grupo;

a) Cadastro de editais: curadores só podem ter acesso de visualização aos projetos inscritos. Hoje eles também podem editar, e isso é perigoso. Solução geral para a ferramenta: colocar níveis de acesso diferenciados (visualizar, editar, criar/excluir) para agentes dentro dos projetos, eventos, agentes e espaços

b) Editais: inscrições rascunhos só devem ser visualizadas e editadas por administradores. Hoje aparece para todos os agentes do projeto;

**Comment by jacksoncastro** [comment]
@geciola  foi criada uma atividade no Core do mapas, pois essa atividade irá mudar totalmente a estrutura da aplicação: hacklabr/mapasculturais#1010

**Comment by nalomysouza** [comment]
foi migrado para a issue https://github.com/hacklabr/mapasculturais/issues/1010
