### ISSUE TITLE
Retirar impossibilidade de colocar arquivos ou links antes de salvar

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#36]
Retirar impossibilidade de colocar arquivos ou links antes de salvar

Obs.: Demanda já existe para a hacklab

**Comment by nalomysouza** [comment]
Ajuste foi sanado com a nova versão atualizada, informando a seguinte mensagem: "Para adicionar arquivos para download ou links, primeiro é preciso salvar o projeto."

**Comment by geciola** [comment]
Então o problema continua. A demanda é que não seja preciso primeiro salvar o projeto para poder inserir arquivos para download ou links.

**Comment by nalomysouza** [comment]
Entendi justamente o inverso, já que adicionar um anexo deixa faria com que obrigatoriamente o projeto seja salvo como "rascunho". Ou seja, como fica os campos obrigatórios? a pessoa teria que adicionar os anexos e preenchelos...

**Comment by jacksoncastro** [comment]
@geciola essa atividade pode ser fechada?

**Comment by nalomysouza** [comment]
Demanda resolvida pela HackLab
