### ISSUE TITLE
Melhorar a ordenação da listagens de resultados dos Eventos

### ISSUE THREAD

**Issue by jacksoncastro** [secultce/mapasculturaisThemeCeara#43]
Melhorar visualização das listagens de resultados. Sugestão: dividir em duas colunas. Boxes com prévias. Ex: Programação da Maloca Dragão (usar isso no site da agenda cultural)

**Comment by nalomysouza** [comment]
Adicionado no novo repositorio https://github.com/secultce/mapasculturais/issues/6
