### ISSUE TITLE
Criar script da base de dados do sinf, Sirh,Siv e VotaCultura para popular o MapaCeara / IdCeará

### ISSUE THREAD

**Issue by geciola** [secultce/mapasculturaisThemeCeara#48]
Cadastrar os usuarios do sinf no login cidadão
Enviar o e-mail para esses usuários no modelo de recuperação de senha.
Referencia: experiência de votação de prioridade do RS (conversar como Donato)

**Comment by geciola** [comment]
Mapear relacionamento entre os bancos de origem e destino.

**Comment by geciola** [comment]
Solicitar scrip feito pelo Rafa

**Comment by nalomysouza** [comment]
Script criado com os dados divididos para as categorias, Profissional da Cultura, Empresa cultural e Grupo Cultural

**Comment by JuniorGiglioli** [comment]
Aguardando script ser enviado pelo @Andreqlp .
