### ISSUE TITLE
Mudar títulos e descrições do campo 4. Agentes

### ISSUE THREAD

**Issue by geciola** [secultce/mapasculturaisThemeCeara#55]
- Substituir "Agente responsável pela inscrição" por "Agente responsável pelo Projeto"
- Substituir descrição por: "Indicar pessoa física que ficará responsável pela execução do Projeto apresentado para este edital".
- Substituir "Instituição Responsável" por "Instituição Proponente"
- Substituir descrição por: "Indicar pessoa jurídica proponente do Projeto apresentado para este edital"

**Comment by nalomysouza** [comment]
As alterações afetam diretamente no arquivo "conf.base.php" que fica fora do thema "Ceara". No caso será necessário pedir apoio ao instituto tim para verificar se é possível. ou acessar nossa aplicação pelo FTP

**Comment by nalomysouza** [comment]
Ajustes realizados
