### ISSUE TITLE
Corrigir página com o resumo das inscrições

### ISSUE THREAD

**Issue by Andreqlp** [secultce/mapasculturaisThemeCeara#60]
- [x] Substituir a legenda do rascunho por essa: Rascunho - utilize essa opção para permitir que o responsável edite e reenvie uma inscrição. 
- [x] Detalhar a informação do total de inscritos, informando o quantidade de rascunhos e de inscrições enviadas. Assim: XX inscrições como rascunho e YY inscrições enviadas
- [x] Inserir a opção de rascunho na caixa de seleção.

![melhorias 202a 20fase-01](https://cloud.githubusercontent.com/assets/14170372/19150393/f6ff8afa-8b9c-11e6-9b45-dd0aaf9ba03a.jpg)

**Comment by JuniorGiglioli** [comment]
@Andreqlp nesse item 2  temos como colocar a quantidade de todos os status ! Seria interessante?

**Comment by uira** [comment]
@JuniorGiglioli Boa idéia. Só tem que ver pra não ficar poluído...

Manda um print aí pra gente ver como fica.

**Comment by JuniorGiglioli** [comment]
![captura de tela de 2016-10-06 11 27 14](https://cloud.githubusercontent.com/assets/12169341/19156335/ead03b10-8bb7-11e6-8254-199a58675543.png)
olha ai @uira !

**Comment by JuniorGiglioli** [comment]
@geciola

**Comment by uira** [comment]
@JuniorGiglioli Acho melhor manter o número total e rascunho em cima e no filtro, dos tipos mostrar os totais

**Comment by Andreqlp** [comment]
@JuniorGiglioli ,  não acho interessante colocar a quantidade de todos os status. O que acho mais importante desse total é acompanhar o andamento das inscrições e, normalmente, os demais status só são avaliados após o fechamento das inscrições. Outro detalhe é que, ao filtrar as inscrições, vocês tem o total de inscrições com o status filtrado.

De todo modo, ter relatório das inscrições é bem importante e acho que esse relatório deveria ser acessado a partir do painel do usuário, onde seria possível comparar editais, ter uma curva de inscrições por dia, saber do perfil dos inscritos e tudo mais.
