### ISSUE TITLE
Link em forma de embed no Facebook

### ISSUE THREAD

**Issue by denisnacif** [secultce/mapasculturaisThemeCeara#65]
O link dos eventos no Mapa não tá gerando imagem do link e sim a imagem padrão
![captura de tela 2016-12-12 as 10 24 23](https://cloud.githubusercontent.com/assets/23640478/21108317/8f17bb04-c073-11e6-81f5-ac55dd65160e.png)

**Comment by nalomysouza** [comment]
Correção efetuada na Branch Principal https://github.com/secultce/mapasculturais
