### ISSUE TITLE
Adicionar nova categoria no campo AREA DE ATUAÇÃO do cadastro de agente

### ISSUE THREAD

**Issue by denisnacif** [secultce/mapasculturaisThemeCeara#67]
![captura de tela 2016-12-14 as 17 08 12](https://cloud.githubusercontent.com/assets/23640478/21198975/49e82c04-c220-11e6-97d2-518764bf5112.png)

>> inserir a categoria HUMOR. @jacksoncastro

**Comment by nalomysouza** [comment]
https://github.com/secultce/mapasculturais/issues/4
