### ISSUE TITLE
Alterar o Selo de "Resultados Verificados"

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#7]
Mudar o nome do Selo de "Resultados Verificados" para "Resultados da Secult"

**Comment by jacksoncastro** [comment]
Só incluir no tema: 
    'search: verified results' => 'Resultados de Governo',

**Comment by nalomysouza** [comment]
Não estamos utilizando os selos contudo a solução 
Só incluir no tema:
'search: verified results' => 'Resultados de Governo'
