### ISSUE TITLE
Reconhecer links de endereços de sites (www / http)

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#8]
No cadastro de eventos, no campo inscrição: o campo deve reconhecer links de todos os endereços que vierem de www e http

**Comment by jacksoncastro** [comment]
Atividade já encontra-se no backlog da CulturaGovBR: culturagovbr/mapasculturais#53

**Comment by nalomysouza** [comment]
migrado para culturagovbr/mapasculturais#53
