### ISSUE TITLE
Estabelecer encerramento do projeto também com base no limite de vagas para inscrição

### ISSUE THREAD

**Issue by nalomysouza** [secultce/mapasculturaisThemeCeara#9]
Por exemplo: Oficina com 100 vagas. O sistema tem que reconhecer quando as vagas se encerrarem pela quantidade de inscritos, não permitindo novas inscrições.

**Comment by jacksoncastro** [comment]
Essa atividade já está em homologação no core do projeto:  hacklabr/mapasculturais#884

**Comment by nalomysouza** [comment]
Foi solucionado no core do mapas hacklabr/mapasculturais#884
